int8 CHANNEL_LEFT=1
int8 CHANNEL_RIGHT=2
int8 CHANNEL_BOTH=3

string request_id
string text
int8 rate
int8 pitch
int8 volume
string lang
string voice
bool force
int32 priority
float32 timeout
int8 channels
---
bool success
string message
---
float32 progress
uint8 status
uint32 read_length
uint32 current_length
string message
