name: Test Building Docker Image and Workspace

on:
  push:
    branches: [ daisukes/docker-buildx-bake-test ]

jobs:
  build-amd64:
    uses: cmu-cabot/cabot-common/.github/workflows/build.yaml@daisukes/docker-buildx-bake-test
    with:
      platform: linux/amd64
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-arm64-desktop:
    uses: cmu-cabot/cabot-common/.github/workflows/build.yaml@daisukes/docker-buildx-bake-test
    with:
      platform: linux/arm64
      target: base ros-core ros-base ros-desktop ros-desktop-custom ros-desktop-custom-mesa
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-arm64-base:
    uses: cmu-cabot/cabot-common/.github/workflows/build.yaml@daisukes/docker-buildx-bake-test
    with:
      platform: linux/arm64
      target: base ros-core ros-base ros-base-custom ros-base-custom-mesa
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
