name: Test Building Docker Image and Workspace

on:
  push:
    branches: [ daisukes/docker-buildx-bake-test ]

jobs:
  build-desktop:
    uses: cmu-cabot/cabot-common/.github/workflows/build.yaml@daisukes/docker-buildx-bake-test
    with:
      target: base ros-core ros-base ros-desktop ros-desktop-custom ros-desktop-custom-mesa
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-base:
    uses: cmu-cabot/cabot-common/.github/workflows/build.yaml@daisukes/docker-buildx-bake-test
    with:
      target: base ros-core ros-base ros-base-custom ros-base-custom-mesa
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
